name: Scriptcooker

# header
header:
  color1: "#FFB646"
  color2: "#FF5467"

# github buttons
githubButton:
  user: simoncozens
  repo: scriptcooker

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

