name: Scriptcooker

# header
header:
  color1: "#080331"
  color2: "#673051"

# github buttons
githubButton:
  user: simoncozens
  repo: scriptcooker

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

